<a href="https://colab.research.google.com/github/Molten-Ice/Kaggle/blob/dev/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1+cu116


Based on: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## Introduction to Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector[0]

tensor(7)

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
#scalars & vectors are lower case.
#matrix & tensors are upper case

In [17]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.3664, 0.0340, 0.4069, 0.8301],
         [0.9207, 0.7984, 0.0909, 0.7376],
         [0.4886, 0.5444, 0.0176, 0.6228]]])

In [18]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
zeros = torch.zeros(size=(3,4))
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
random_tensor.dtype

torch.float32

In [23]:
range1 = torch.arange(0, 100, step = 5) # BAD NAME FOR A VARIABLE - breaks everything
range1

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [24]:
ten_zeros = torch.zeros_like(input=range1)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor*float_32_tensor


tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [30]:
float_32_tensor.device

device(type='cpu')

In [31]:
tensor = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6]).T
tensor*tensor2

<ipython-input-31-795859eb9963>:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  tensor2 = torch.tensor([4, 5, 6]).T


tensor([ 4, 10, 18])

In [32]:
tensor2*tensor

tensor([ 4, 10, 18])

In [33]:
torch.matmul(tensor, tensor.T)

tensor(14)

In [34]:
%%time
torch.matmul(tensor, tensor.T)

CPU times: user 0 ns, sys: 126 µs, total: 126 µs
Wall time: 134 µs


tensor(14)

In [35]:
tensor.shape[0]

3

In [36]:
tensor_test = torch.tensor([2, 3, 4])
tensor_test

tensor([2, 3, 4])

In [37]:
%%time
torch.matmul(tensor_test, tensor_test.T)

CPU times: user 99 µs, sys: 18 µs, total: 117 µs
Wall time: 123 µs


tensor(29)

In [38]:
%%time
value = 0
for i in range(tensor.shape[0]):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.72 ms, sys: 0 ns, total: 2.72 ms
Wall time: 8.02 ms


In [39]:
tensor[0]

tensor(1)

In [41]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 2))

tensor([[1.5144, 2.4149],
        [1.6884, 2.5567],
        [2.1913, 3.0021]])

In [44]:
tensor_A = torch.tensor([[1,2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7,10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [46]:
tensor_A.size()

torch.Size([3, 2])

In [48]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [53]:
torch.mean(x.type(torch.float32))


tensor(45.)

In [55]:
x.type(torch.float32).mean()

tensor(45.)

In [57]:
torch.sum(x)

tensor(450)

In [58]:
x, x.argmin()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(0))

In [59]:
x.argmax()

tensor(9)

# Reshaping, stacking, squeezing and unsqueezing tensors

In [66]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [67]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
x_reshaped = x.reshape(9, 1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [69]:
x = torch.arange(1., 13.)
x_reshaped = x.reshape(3, 4)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [71]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [73]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [74]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [79]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [89]:
torch.unsqueeze(x_stacked, dim = 2)

tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]],

        [[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]],

        [[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]],

        [[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])