<a href="https://colab.research.google.com/github/Molten-Ice/Kaggle/blob/dev/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1+cu116


Based on: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## Introduction to Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector[0]

tensor(7)

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
#scalars & vectors are lower case.
#matrix & tensors are upper case

In [ ]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.1367, 0.7120, 0.1630, 0.6208],
         [0.4311, 0.1332, 0.1828, 0.0537],
         [0.0387, 0.3755, 0.9303, 0.4874]]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
range1 = torch.arange(0, 100, step = 5) # BAD NAME FOR A VARIABLE - breaks everything
range1

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [ ]:
ten_zeros = torch.zeros_like(input=range1)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor


tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
float_32_tensor.device

device(type='cpu')

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6]).T
tensor*tensor2

<ipython-input-31-795859eb9963>:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3277.)
  tensor2 = torch.tensor([4, 5, 6]).T


tensor([ 4, 10, 18])

In [ ]:
tensor2*tensor

tensor([ 4, 10, 18])

In [ ]:
torch.matmul(tensor, tensor.T)

tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor.T)

CPU times: user 1.74 ms, sys: 0 ns, total: 1.74 ms
Wall time: 2.62 ms


tensor(14)

In [ ]:
tensor.shape[0]

3

In [ ]:
tensor_test = torch.tensor([2, 3, 4])
tensor_test

tensor([2, 3, 4])

In [ ]:
%%time
torch.matmul(tensor_test, tensor_test.T)

CPU times: user 1.78 ms, sys: 0 ns, total: 1.78 ms
Wall time: 3.94 ms


tensor(29)

In [ ]:
%%time
value = 0
for i in range(tensor.shape[0]):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.08 ms, sys: 0 ns, total: 3.08 ms
Wall time: 5.65 ms


In [ ]:
tensor[0]

tensor(1)

In [ ]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 2))

tensor([[1.9917, 2.2048],
        [2.6762, 2.7709],
        [2.1755, 2.1783]])

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7,10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

In [ ]:
tensor_A.size()

torch.Size([3, 2])

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32))


tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
x, x.argmin()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(0))

In [ ]:
x.argmax()

tensor(9)

# Reshaping, stacking, squeezing and unsqueezing tensors

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x = torch.arange(1., 13.)
x_reshaped = x.reshape(3, 4)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.unsqueeze(x, dim = 0)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.unsqueeze(x, dim = 1)

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x_stacked.shape

torch.Size([4, 9])

In [ ]:
torch.permute(x_stacked, (1, 0))

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_original = torch.rand(size = (224, 224, 3))
x_permuted = x_original.permute((2, 0 , 1))
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x_permuted[0, 0, 0] = 5
x_original[0:2, 0:2, 0:2]

tensor([[[5.0000, 0.8092],
         [0.7322, 0.8105]],

        [[0.6987, 0.7422],
         [0.4449, 0.3321]]])

# Indexing

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[0, :, 2]

tensor([3, 6, 9])

 # NumPy

In [ ]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array[0] = 5
array, tensor

(array([5., 2., 3., 4., 5., 6., 7.]),
 tensor([5., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0337, 0.0454, 0.6262, 0.0234],
        [0.5871, 0.8464, 0.4463, 0.5607],
        [0.2434, 0.9279, 0.0496, 0.2014]])
tensor([[0.4559, 0.5389, 0.5794, 0.0550],
        [0.1917, 0.0920, 0.3319, 0.9988],
        [0.7960, 0.4288, 0.3172, 0.0815]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Random seed
RANDOM_SEED = 3

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.0043, 0.1056, 0.2858, 0.0270],
        [0.4716, 0.0601, 0.7719, 0.7437],
        [0.5944, 0.8879, 0.4510, 0.7995]])
tensor([[0.0043, 0.1056, 0.2858, 0.0270],
        [0.4716, 0.0601, 0.7719, 0.7437],
        [0.5944, 0.8879, 0.4510, 0.7995]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
torch.cuda.is_available()

False

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f'device: {device}')

device: cpu


In [ ]:
tensor = torch.tensor([1, 2, 3], device = "cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [ ]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])